### ISSUE TITLE
Crash on Ice Levels if UFO hit by rock or girl

### ISSUE THREAD

**Issue by leek2** [yancharkin/SpelunkyClassicHD#15]
I'm a huge fan, this is a great version of Spelunky.  But I have crashed on this bug so many times.  If I hit a UFO with a rock or a girl, the game crashes with the error message below.  A pot will kill the UFO properly though.

Error when rock used:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object oItem:

Unable to find any instance for object index '112342'
at gml_Object_oItem_Step_0
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_oItem_Step_0 (line -1)

Error when girl used:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object oItem:

Unable to find any instance for object index '112563'
at gml_Object_oItem_Step_0
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_oItem_Step_0 (line -1)
called from - gml_Object_oDamsel_Step_0 (line -1) - <unknown source line>

**Comment by yancharkin** [comment]
Fixed. But there is a chance that I broke something else. Test this build for a few days, if everything is OK, I'll release it. 
https://mega.nz/folder/CtZkxZSY#Wi0W0A2A5DCnpknqvbCKUg
I assume you're using Windows? If not, let me know.
Debug build allows you to make quick test by pressing F4.

**Comment by leek2** [comment]
Yes, I'm using Windows.  I've been testing for a few days and haven't had anymore crashes.  But I still can't beat the game, so I can't promise to have tested everything.

Thanks

**Comment by yancharkin** [comment]
OK. Thanks for testing.
